# -*- coding: utf-8 -*-
"""Fundamentals of Data Science - EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0kb0LdoKiaccTwdlcYSMs-TJi5Od75W
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Create a dummy DataFrame with more data for demonstration
data = {
    'Year': [2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027],
    'Youth Hostels Constructed (UOM:Number), Scaling Factor:1': [10, 12, 15, 18, 20, 23, 25, 28],
    'Other Column 1': [100, 120, 150, 180, 200, 230, 250, 280],
    'Other Column 2': [50, 60, 75, 90, 100, 115, 125, 140]
}
df = pd.DataFrame(data)

df.shape
df.info()
df.isnull().sum()
df.describe()
df = df.rename(columns={
    'Youth Hostels Constructed (UOM:Number), Scaling Factor:1':'Youth Hostels'
})
df['Youth Hostels']= df['Youth Hostels'].astype(int)
# The drop was causing an error, I'll remove it for now
# df.drop('Youth Hostels',axis=1)

plt.figure(figsize=(10, 6))
plt.plot(df['Year'], df['Youth Hostels'], marker='o', linestyle='-')
plt.title('Youth Hostels Constructed Over Time')
plt.xlabel('Year')
plt.ylabel('Number of Youth Hostels')
plt.grid(True)
plt.show()